version: "3.9"

services:
  server:
    build: ./server
    env_file:
      - .env
      - server.env
    ports:
      - "8000:${SERVER_DOCKER_PORT}"
    networks:
      - trspo 

  client:
    build: ./client
    env_file:
      - client.env
    ports:
      - "8001:8000"
    depends_on:
      - server
    networks:
      - trspo

networks:
  trspo:
    driver: bridge
    external: false